name: Update README
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours (more frequent updates)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Content
        run: |
          # 1. Update timestamp
          sed -i "s/Last Update: .*/Last Update: $(date +'%Y-%m-%d %H:%M')/" README.md
          
          # 2. Force DevCard refresh
          sed -i "s|devcards.*png?[^\"]*|devcards/v2/dLZFgTpZ1LsHsVHSaKXUJ.png?r=$((RANDOM))\&theme=nightowl|" README.md

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🔄 Updated README + DevCard Refresh" || exit 0
          git pull --rebase origin main
          git push origin main
