name: Update README
on:
  schedule:
    - cron: '0 12 * * *'  # Daily at noon UTC
  workflow_dispatch:      # Manual trigger option

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Required for pushing changes

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full git history

      - name: Update Date
        run: |
          sed -i "s/Last Update: .*/Last Update: $(date +'%Y-%m-%d %H:%M')/" README.md

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "📅 Automated update" || exit 0
          git pull --rebase origin main
          git push origin main
